stages:
  - Build
  - UnitTest


Build:
  stage: Build
  tags:
    - cpp
  script:
  - cmake CMakeLists.txt
  - make
  - ls 
  
Test:
  stage: UnitTest
  tags:
    - python
  script:
  - python UnitTest.py
