stages:
  - CppCheck
  - ClangFormat
  - Build and Test

ClangFormat:
  stage: ClangFormat
  tags:
    - cpp
  script:
  - find . -iname *.h -o -iname *.cpp | xargs clang-format -i -style=file 
  
CppCheck:
  stage: CppCheck
  tags:
    - cpp
  script:
  - cppcheck . --enable=all --suppress=missingIncludeSystem --check-config -I include/

Build:
  stage: Build and Test
  tags:
    - cpp,python
  script:
  - cmake CMakeLists.txt
  - make
  - python UnitTest.py