stages:
  - CppCheck
  - Build and Test

CppCheck:
  stage: CppCheck
  tags:
    - cpp
  script:
  - cppcheck -I include/ -I src/ main.cpp

Build:
  stage: Build and Test
  tags:
    - cpp,python
  script:
  - cmake CMakeLists.txt
  - make
  - python UnitTest.py