language: cpp
sudo: required
matrix:
  include:
  - os: linux
    dist: trusty
    compiler: gcc
  - os: linux
    dist: trusty
    compiler: clang
  - os: linux
    dist: trusty
    compiler: clang
    env: CLANG=6.0 SAN_FLAGS="--enable-asan --enable-ubsan"
  - os: osx
    osx_image: xcode9.2
    compiler: clang
  allow_failures:
  - os: osx
  - env: CLANG=6.0 SAN_FLAGS="--enable-asan --enable-ubsan"

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y cmake python
  - sudo pip install --upgrade pip
  - sudo pip install codecov

script:
  - cmake CMakeLists.txt && make
  - cp cppstack unittest
  - coverage run unittest/UnitTest.py
 
after_success:
  - bash <(curl -s https://codecov.io/bash)
