language: c
sudo: required
compiler: gcc
dist: trusty

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y cmake

script:
  - cmake CMakeLists.txt && make
  - ./stack "5 5 /"
  - ./stack "5 1 2 + 4 x + 3 - 2 /"
  - ./stack "8 2 5 x + 1 3 2 x + 4 - /"