language: cpp
sudo: required
matrix:
  include:
  - os: linux
    dist: trusty
    compiler: gcc
  - os: linux
    dist: trusty
    compiler: clang
  - os: osx
    osx_image: xcode9.2
    compiler: clang
  allow_failures:
  - os: osx

install:
  - sudo pip install -r requirements.txt --user

script:
  - cmake CMakeLists.txt && make
  - coverage run UnitTest.py
 
after_success:
  - bash <(curl -s https://codecov.io/bash)
