language: cpp
sudo: required
matrix:
  include:
  - os: linux
    dist: trusty
    compiler: gcc
  - os: linux
    dist: trusty
    compiler: clang
  - os: osx
    osx_image: xcode11
    compiler: clang
  allow_failures:
  - os: osx

install:
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - sudo python get-pip.py
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt --user

script:
  - mkdir build
  - cd build && cmake ../ && make
  - coverage run UnitTest.py
 
after_success:
  - bash <(curl -s https://codecov.io/bash)
