language: cpp
sudo: required
matrix:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
  - os: linux
    dist: bionic
    compiler: clang
  - os: osx
    osx_image: xcode11
    compiler: clang
  allow_failures:
  - os: osx

script:
  - mkdir build
  - cd build && cmake ../ && make
  - ln -s ccpstack ../ 
  - ln -s ccpstack_test ../
  - ./ccpstack_test
 

